name: Deploy Dist folder
#on: [push, workflow_dispatch]
on: 
  push:
    branches: 
      - main
    paths-ignore:
      - 'frontend/node_modules/**'
      - 'frontend/dist/**'
    #  - 'frontend/package-lock.json'
    #  - 'frontend/package.json'
      - 'frontend/README.md'
      - 'frontend/LICENSE'
      - 'frontend/.gitignore'
      - '.github/workflows/*'
  workflow_dispatch:
                 
jobs:
    test:            # Ime joba
        runs-on: ubuntu-latest  # Okruženje
        steps:
          - name: Checkout      #kloniraj repo
            uses: actions/checkout@v4
          - name: Setup Node and install dependencies
            uses: ./.github/setupnode
          
          # - name: Install Backend Dependencies
          #   working-directory: ./backend
          #   run: npm install

          - name: Run Frontend Tests
            working-directory: ./frontend
            run: npm test

          # - name: Run Backend Tests
          #   working-directory: ./backend
          #   run: npm test

          - name: Completed
            run: echo "Test job was completed"
    build:
      needs: test
      runs-on: ubuntu-latest  # Okruženje
      steps:
        - name: Checkout      #kloniraj repo
          uses: actions/checkout@v4      
        - name: Setup Node and install dependencies
          uses: ./.github/setupnode

        # - name: Install Backend Dependencies
        #   working-directory: ./backend
        #   run: npm install

        - name: Run Frontend Build
          working-directory: ./frontend
          run: npm run build 

        # - name: Run Backend Build
        #   working-directory: ./backend
        #   run: npm run build

        - name: Completed
          run: echo "Build job was completed"      

        - name: Upload dist Artifacts frontend
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: ./frontend/dist

    deploy:
      needs: build
      runs-on: ubuntu-latest  
      steps:
        - name: Download dist Artifacts
          uses: actions/download-artifact@v4
          with:
            name: dist-files
            path: ./frontend/dist

        - name: Deploy Dist    
          run: |
            echo "Deploying files below"
            ls dist
            echo "Deploying completed"
